-- Data.Int: the Haskell 2010 library module (Report 2010), for Yale
-- Haskell's Haskell 98 dialect.  Each type is a newtype
-- over Int (Int64 over Integer, since Int is a 63-bit fixnum) holding the
-- value normalised to its range, so arithmetic wraps.
-- Generated by tools/gen/gen-intword.py; edit that, not this file.
module Data.Int (Int, Int8, Int16, Int32, Int64) where

import Ix
import Data.Bits

-- Int8: signed 8-bit integers, kept normalised in an Int
newtype Int8 = Int8 Int deriving (Eq, Ord)

normInt8 :: Int -> Int
normInt8 x = let m = x `mod` 256 in if m > 127 then m - 256 else m

normInt8I :: Integer -> Int
normInt8I i = fromInteger (let m = i `mod` 256 in if m > 127 then m - 256 else m)

liftInt81 :: (Int -> Int) -> Int8 -> Int8
liftInt81 f (Int8 x) = Int8 (normInt8 (f x))

liftInt82 :: (Int -> Int -> Int) -> Int8 -> Int8 -> Int8
liftInt82 f (Int8 x) (Int8 y) = Int8 (normInt8 (f x y))

instance Show Int8 where
  showsPrec p (Int8 x) = showsPrec p x

instance Read Int8 where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Int8 where
  minBound = Int8 (-128)
  maxBound = Int8 127

instance Num Int8 where
  (+)         = liftInt82 (+)
  (-)         = liftInt82 (-)
  (*)         = liftInt82 (*)
  negate      = liftInt81 negate
  abs         = liftInt81 abs
  signum      = liftInt81 signum
  fromInteger i = Int8 (normInt8I i)

instance Real Int8 where
  toRational x = toRational (toInteger x)

instance Enum Int8 where
  succ x | x == maxBound = error "Enum.succ{Int8}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Int8}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Int8) && toInteger i <= toInteger (maxBound :: Int8)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Int8}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Int8 where
  quot (Int8 x) (Int8 y) = if y == -1 && x == -128 then error "arithmetic overflow" else Int8 (normInt8 (quot x y))
  rem (Int8 x) (Int8 y)  = Int8 (normInt8 (rem x y))
  div (Int8 x) (Int8 y)  = if y == -1 && x == -128 then error "arithmetic overflow" else Int8 (normInt8 (div x y))
  mod (Int8 x) (Int8 y)  = Int8 (normInt8 (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Int8 x) = toInteger x

instance Ix Int8 where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Int8}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Int8 where
  (.&.)        = liftInt82 (.&.)
  (.|.)        = liftInt82 (.|.)
  xor          = liftInt82 xor
  complement   = liftInt81 complement
  shift (Int8 x) i = Int8 (normInt8 (shift x i))
  rotate (Int8 x) i = let { j = i `mod` 8; u = (x `mod` 256) }
                     in Int8 (normInt8 ((u `shiftL` j) .|. (u `shiftR` (8 - j))))
  testBit (Int8 x) i = i < 8 && testBit x i
  bitSize _    = 8
  isSigned _   = True
  popCount (Int8 x) = popCount (x `mod` 256)

-- Int16: signed 16-bit integers, kept normalised in an Int
newtype Int16 = Int16 Int deriving (Eq, Ord)

normInt16 :: Int -> Int
normInt16 x = let m = x `mod` 65536 in if m > 32767 then m - 65536 else m

normInt16I :: Integer -> Int
normInt16I i = fromInteger (let m = i `mod` 65536 in if m > 32767 then m - 65536 else m)

liftInt161 :: (Int -> Int) -> Int16 -> Int16
liftInt161 f (Int16 x) = Int16 (normInt16 (f x))

liftInt162 :: (Int -> Int -> Int) -> Int16 -> Int16 -> Int16
liftInt162 f (Int16 x) (Int16 y) = Int16 (normInt16 (f x y))

instance Show Int16 where
  showsPrec p (Int16 x) = showsPrec p x

instance Read Int16 where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Int16 where
  minBound = Int16 (-32768)
  maxBound = Int16 32767

instance Num Int16 where
  (+)         = liftInt162 (+)
  (-)         = liftInt162 (-)
  (*)         = liftInt162 (*)
  negate      = liftInt161 negate
  abs         = liftInt161 abs
  signum      = liftInt161 signum
  fromInteger i = Int16 (normInt16I i)

instance Real Int16 where
  toRational x = toRational (toInteger x)

instance Enum Int16 where
  succ x | x == maxBound = error "Enum.succ{Int16}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Int16}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Int16) && toInteger i <= toInteger (maxBound :: Int16)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Int16}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Int16 where
  quot (Int16 x) (Int16 y) = if y == -1 && x == -32768 then error "arithmetic overflow" else Int16 (normInt16 (quot x y))
  rem (Int16 x) (Int16 y)  = Int16 (normInt16 (rem x y))
  div (Int16 x) (Int16 y)  = if y == -1 && x == -32768 then error "arithmetic overflow" else Int16 (normInt16 (div x y))
  mod (Int16 x) (Int16 y)  = Int16 (normInt16 (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Int16 x) = toInteger x

instance Ix Int16 where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Int16}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Int16 where
  (.&.)        = liftInt162 (.&.)
  (.|.)        = liftInt162 (.|.)
  xor          = liftInt162 xor
  complement   = liftInt161 complement
  shift (Int16 x) i = Int16 (normInt16 (shift x i))
  rotate (Int16 x) i = let { j = i `mod` 16; u = (x `mod` 65536) }
                     in Int16 (normInt16 ((u `shiftL` j) .|. (u `shiftR` (16 - j))))
  testBit (Int16 x) i = i < 16 && testBit x i
  bitSize _    = 16
  isSigned _   = True
  popCount (Int16 x) = popCount (x `mod` 65536)

-- Int32: signed 32-bit integers, kept normalised in an Int
newtype Int32 = Int32 Int deriving (Eq, Ord)

normInt32 :: Int -> Int
normInt32 x = let m = x `mod` 4294967296 in if m > 2147483647 then m - 4294967296 else m

normInt32I :: Integer -> Int
normInt32I i = fromInteger (let m = i `mod` 4294967296 in if m > 2147483647 then m - 4294967296 else m)

liftInt321 :: (Int -> Int) -> Int32 -> Int32
liftInt321 f (Int32 x) = Int32 (normInt32 (f x))

liftInt322 :: (Int -> Int -> Int) -> Int32 -> Int32 -> Int32
liftInt322 f (Int32 x) (Int32 y) = Int32 (normInt32 (f x y))

instance Show Int32 where
  showsPrec p (Int32 x) = showsPrec p x

instance Read Int32 where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Int32 where
  minBound = Int32 (-2147483648)
  maxBound = Int32 2147483647

instance Num Int32 where
  (+)         = liftInt322 (+)
  (-)         = liftInt322 (-)
  (*)         = liftInt322 (*)
  negate      = liftInt321 negate
  abs         = liftInt321 abs
  signum      = liftInt321 signum
  fromInteger i = Int32 (normInt32I i)

instance Real Int32 where
  toRational x = toRational (toInteger x)

instance Enum Int32 where
  succ x | x == maxBound = error "Enum.succ{Int32}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Int32}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Int32) && toInteger i <= toInteger (maxBound :: Int32)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Int32}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Int32 where
  quot (Int32 x) (Int32 y) = if y == -1 && x == -2147483648 then error "arithmetic overflow" else Int32 (normInt32 (quot x y))
  rem (Int32 x) (Int32 y)  = Int32 (normInt32 (rem x y))
  div (Int32 x) (Int32 y)  = if y == -1 && x == -2147483648 then error "arithmetic overflow" else Int32 (normInt32 (div x y))
  mod (Int32 x) (Int32 y)  = Int32 (normInt32 (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Int32 x) = toInteger x

instance Ix Int32 where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Int32}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Int32 where
  (.&.)        = liftInt322 (.&.)
  (.|.)        = liftInt322 (.|.)
  xor          = liftInt322 xor
  complement   = liftInt321 complement
  shift (Int32 x) i = Int32 (normInt32 (shift x i))
  rotate (Int32 x) i = let { j = i `mod` 32; u = (x `mod` 4294967296) }
                     in Int32 (normInt32 ((u `shiftL` j) .|. (u `shiftR` (32 - j))))
  testBit (Int32 x) i = i < 32 && testBit x i
  bitSize _    = 32
  isSigned _   = True
  popCount (Int32 x) = popCount (x `mod` 4294967296)

-- Int64: signed 64-bit integers, kept normalised in an Integer
newtype Int64 = Int64 Integer deriving (Eq, Ord)

normInt64 :: Integer -> Integer
normInt64 x = let m = x `mod` 18446744073709551616 in if m > 9223372036854775807 then m - 18446744073709551616 else m

normInt64I :: Integer -> Integer
normInt64I i = fromInteger (let m = i `mod` 18446744073709551616 in if m > 9223372036854775807 then m - 18446744073709551616 else m)

liftInt641 :: (Integer -> Integer) -> Int64 -> Int64
liftInt641 f (Int64 x) = Int64 (normInt64 (f x))

liftInt642 :: (Integer -> Integer -> Integer) -> Int64 -> Int64 -> Int64
liftInt642 f (Int64 x) (Int64 y) = Int64 (normInt64 (f x y))

instance Show Int64 where
  showsPrec p (Int64 x) = showsPrec p x

instance Read Int64 where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Int64 where
  minBound = Int64 (-9223372036854775808)
  maxBound = Int64 9223372036854775807

instance Num Int64 where
  (+)         = liftInt642 (+)
  (-)         = liftInt642 (-)
  (*)         = liftInt642 (*)
  negate      = liftInt641 negate
  abs         = liftInt641 abs
  signum      = liftInt641 signum
  fromInteger i = Int64 (normInt64I i)

instance Real Int64 where
  toRational x = toRational (toInteger x)

instance Enum Int64 where
  succ x | x == maxBound = error "Enum.succ{Int64}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Int64}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Int64) && toInteger i <= toInteger (maxBound :: Int64)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Int64}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Int64 where
  quot (Int64 x) (Int64 y) = if y == -1 && x == -9223372036854775808 then error "arithmetic overflow" else Int64 (normInt64 (quot x y))
  rem (Int64 x) (Int64 y)  = Int64 (normInt64 (rem x y))
  div (Int64 x) (Int64 y)  = if y == -1 && x == -9223372036854775808 then error "arithmetic overflow" else Int64 (normInt64 (div x y))
  mod (Int64 x) (Int64 y)  = Int64 (normInt64 (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Int64 x) = toInteger x

instance Ix Int64 where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Int64}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Int64 where
  (.&.)        = liftInt642 (.&.)
  (.|.)        = liftInt642 (.|.)
  xor          = liftInt642 xor
  complement   = liftInt641 complement
  shift (Int64 x) i = Int64 (normInt64 (shift x i))
  rotate (Int64 x) i = let { j = i `mod` 64; u = (x `mod` 18446744073709551616) }
                     in Int64 (normInt64 ((u `shiftL` j) .|. (u `shiftR` (64 - j))))
  testBit (Int64 x) i = i < 64 && testBit x i
  bitSize _    = 64
  isSigned _   = True
  popCount (Int64 x) = popCount (x `mod` 18446744073709551616)
