-- Data.Word: the Haskell 2010 library module (Report 2010), for Yale
-- Haskell's Haskell 98 dialect.  Each type is a newtype
-- over Int (Word64 and Word over Integer) holding the value reduced
-- modulo 2^n, so arithmetic wraps.  Word is 64 bits, as in GHC.
-- Generated by tools/gen/gen-intword.py; edit that, not this file.
module Data.Word (Word, Word8, Word16, Word32, Word64) where

import Ix
import Data.Bits

-- Word8: unsigned 8-bit integers, kept normalised in an Int
newtype Word8 = Word8 Int deriving (Eq, Ord)

normWord8 :: Int -> Int
normWord8 x = x `mod` 256

normWord8I :: Integer -> Int
normWord8I i = fromInteger (i `mod` 256)

liftWord81 :: (Int -> Int) -> Word8 -> Word8
liftWord81 f (Word8 x) = Word8 (normWord8 (f x))

liftWord82 :: (Int -> Int -> Int) -> Word8 -> Word8 -> Word8
liftWord82 f (Word8 x) (Word8 y) = Word8 (normWord8 (f x y))

instance Show Word8 where
  showsPrec p (Word8 x) = showsPrec p x

instance Read Word8 where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Word8 where
  minBound = Word8 (0)
  maxBound = Word8 255

instance Num Word8 where
  (+)         = liftWord82 (+)
  (-)         = liftWord82 (-)
  (*)         = liftWord82 (*)
  negate      = liftWord81 negate
  abs         = id
  signum      = liftWord81 signum
  fromInteger i = Word8 (normWord8I i)

instance Real Word8 where
  toRational x = toRational (toInteger x)

instance Enum Word8 where
  succ x | x == maxBound = error "Enum.succ{Word8}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Word8}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Word8) && toInteger i <= toInteger (maxBound :: Word8)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Word8}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Word8 where
  quot (Word8 x) (Word8 y) = Word8 (normWord8 (quot x y))
  rem (Word8 x) (Word8 y)  = Word8 (normWord8 (rem x y))
  div (Word8 x) (Word8 y)  = Word8 (normWord8 (div x y))
  mod (Word8 x) (Word8 y)  = Word8 (normWord8 (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Word8 x) = toInteger x

instance Ix Word8 where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Word8}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Word8 where
  (.&.)        = liftWord82 (.&.)
  (.|.)        = liftWord82 (.|.)
  xor          = liftWord82 xor
  complement   = liftWord81 complement
  shift (Word8 x) i = Word8 (normWord8 (shift x i))
  rotate (Word8 x) i = let { j = i `mod` 8; u = x }
                     in Word8 (normWord8 ((u `shiftL` j) .|. (u `shiftR` (8 - j))))
  testBit (Word8 x) i = i < 8 && testBit x i
  bitSize _    = 8
  isSigned _   = False
  popCount (Word8 x) = popCount x

-- Word16: unsigned 16-bit integers, kept normalised in an Int
newtype Word16 = Word16 Int deriving (Eq, Ord)

normWord16 :: Int -> Int
normWord16 x = x `mod` 65536

normWord16I :: Integer -> Int
normWord16I i = fromInteger (i `mod` 65536)

liftWord161 :: (Int -> Int) -> Word16 -> Word16
liftWord161 f (Word16 x) = Word16 (normWord16 (f x))

liftWord162 :: (Int -> Int -> Int) -> Word16 -> Word16 -> Word16
liftWord162 f (Word16 x) (Word16 y) = Word16 (normWord16 (f x y))

instance Show Word16 where
  showsPrec p (Word16 x) = showsPrec p x

instance Read Word16 where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Word16 where
  minBound = Word16 (0)
  maxBound = Word16 65535

instance Num Word16 where
  (+)         = liftWord162 (+)
  (-)         = liftWord162 (-)
  (*)         = liftWord162 (*)
  negate      = liftWord161 negate
  abs         = id
  signum      = liftWord161 signum
  fromInteger i = Word16 (normWord16I i)

instance Real Word16 where
  toRational x = toRational (toInteger x)

instance Enum Word16 where
  succ x | x == maxBound = error "Enum.succ{Word16}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Word16}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Word16) && toInteger i <= toInteger (maxBound :: Word16)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Word16}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Word16 where
  quot (Word16 x) (Word16 y) = Word16 (normWord16 (quot x y))
  rem (Word16 x) (Word16 y)  = Word16 (normWord16 (rem x y))
  div (Word16 x) (Word16 y)  = Word16 (normWord16 (div x y))
  mod (Word16 x) (Word16 y)  = Word16 (normWord16 (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Word16 x) = toInteger x

instance Ix Word16 where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Word16}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Word16 where
  (.&.)        = liftWord162 (.&.)
  (.|.)        = liftWord162 (.|.)
  xor          = liftWord162 xor
  complement   = liftWord161 complement
  shift (Word16 x) i = Word16 (normWord16 (shift x i))
  rotate (Word16 x) i = let { j = i `mod` 16; u = x }
                     in Word16 (normWord16 ((u `shiftL` j) .|. (u `shiftR` (16 - j))))
  testBit (Word16 x) i = i < 16 && testBit x i
  bitSize _    = 16
  isSigned _   = False
  popCount (Word16 x) = popCount x

-- Word32: unsigned 32-bit integers, kept normalised in an Int
newtype Word32 = Word32 Int deriving (Eq, Ord)

normWord32 :: Int -> Int
normWord32 x = x `mod` 4294967296

normWord32I :: Integer -> Int
normWord32I i = fromInteger (i `mod` 4294967296)

liftWord321 :: (Int -> Int) -> Word32 -> Word32
liftWord321 f (Word32 x) = Word32 (normWord32 (f x))

liftWord322 :: (Int -> Int -> Int) -> Word32 -> Word32 -> Word32
liftWord322 f (Word32 x) (Word32 y) = Word32 (normWord32 (f x y))

instance Show Word32 where
  showsPrec p (Word32 x) = showsPrec p x

instance Read Word32 where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Word32 where
  minBound = Word32 (0)
  maxBound = Word32 4294967295

instance Num Word32 where
  (+)         = liftWord322 (+)
  (-)         = liftWord322 (-)
  (*)         = liftWord322 (*)
  negate      = liftWord321 negate
  abs         = id
  signum      = liftWord321 signum
  fromInteger i = Word32 (normWord32I i)

instance Real Word32 where
  toRational x = toRational (toInteger x)

instance Enum Word32 where
  succ x | x == maxBound = error "Enum.succ{Word32}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Word32}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Word32) && toInteger i <= toInteger (maxBound :: Word32)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Word32}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Word32 where
  quot (Word32 x) (Word32 y) = Word32 (normWord32 (quot x y))
  rem (Word32 x) (Word32 y)  = Word32 (normWord32 (rem x y))
  div (Word32 x) (Word32 y)  = Word32 (normWord32 (div x y))
  mod (Word32 x) (Word32 y)  = Word32 (normWord32 (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Word32 x) = toInteger x

instance Ix Word32 where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Word32}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Word32 where
  (.&.)        = liftWord322 (.&.)
  (.|.)        = liftWord322 (.|.)
  xor          = liftWord322 xor
  complement   = liftWord321 complement
  shift (Word32 x) i = Word32 (normWord32 (shift x i))
  rotate (Word32 x) i = let { j = i `mod` 32; u = x }
                     in Word32 (normWord32 ((u `shiftL` j) .|. (u `shiftR` (32 - j))))
  testBit (Word32 x) i = i < 32 && testBit x i
  bitSize _    = 32
  isSigned _   = False
  popCount (Word32 x) = popCount x

-- Word64: unsigned 64-bit integers, kept normalised in an Integer
newtype Word64 = Word64 Integer deriving (Eq, Ord)

normWord64 :: Integer -> Integer
normWord64 x = x `mod` 18446744073709551616

normWord64I :: Integer -> Integer
normWord64I i = fromInteger (i `mod` 18446744073709551616)

liftWord641 :: (Integer -> Integer) -> Word64 -> Word64
liftWord641 f (Word64 x) = Word64 (normWord64 (f x))

liftWord642 :: (Integer -> Integer -> Integer) -> Word64 -> Word64 -> Word64
liftWord642 f (Word64 x) (Word64 y) = Word64 (normWord64 (f x y))

instance Show Word64 where
  showsPrec p (Word64 x) = showsPrec p x

instance Read Word64 where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Word64 where
  minBound = Word64 (0)
  maxBound = Word64 18446744073709551615

instance Num Word64 where
  (+)         = liftWord642 (+)
  (-)         = liftWord642 (-)
  (*)         = liftWord642 (*)
  negate      = liftWord641 negate
  abs         = id
  signum      = liftWord641 signum
  fromInteger i = Word64 (normWord64I i)

instance Real Word64 where
  toRational x = toRational (toInteger x)

instance Enum Word64 where
  succ x | x == maxBound = error "Enum.succ{Word64}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Word64}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Word64) && toInteger i <= toInteger (maxBound :: Word64)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Word64}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Word64 where
  quot (Word64 x) (Word64 y) = Word64 (normWord64 (quot x y))
  rem (Word64 x) (Word64 y)  = Word64 (normWord64 (rem x y))
  div (Word64 x) (Word64 y)  = Word64 (normWord64 (div x y))
  mod (Word64 x) (Word64 y)  = Word64 (normWord64 (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Word64 x) = toInteger x

instance Ix Word64 where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Word64}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Word64 where
  (.&.)        = liftWord642 (.&.)
  (.|.)        = liftWord642 (.|.)
  xor          = liftWord642 xor
  complement   = liftWord641 complement
  shift (Word64 x) i = Word64 (normWord64 (shift x i))
  rotate (Word64 x) i = let { j = i `mod` 64; u = x }
                     in Word64 (normWord64 ((u `shiftL` j) .|. (u `shiftR` (64 - j))))
  testBit (Word64 x) i = i < 64 && testBit x i
  bitSize _    = 64
  isSigned _   = False
  popCount (Word64 x) = popCount x

-- Word: unsigned 64-bit integers, kept normalised in an Integer
newtype Word = Word Integer deriving (Eq, Ord)

normWord :: Integer -> Integer
normWord x = x `mod` 18446744073709551616

normWordI :: Integer -> Integer
normWordI i = fromInteger (i `mod` 18446744073709551616)

liftWord1 :: (Integer -> Integer) -> Word -> Word
liftWord1 f (Word x) = Word (normWord (f x))

liftWord2 :: (Integer -> Integer -> Integer) -> Word -> Word -> Word
liftWord2 f (Word x) (Word y) = Word (normWord (f x y))

instance Show Word where
  showsPrec p (Word x) = showsPrec p x

instance Read Word where
  readsPrec p s = [(fromInteger i, r) | (i, r) <- readsPrec p s]

instance Bounded Word where
  minBound = Word (0)
  maxBound = Word 18446744073709551615

instance Num Word where
  (+)         = liftWord2 (+)
  (-)         = liftWord2 (-)
  (*)         = liftWord2 (*)
  negate      = liftWord1 negate
  abs         = id
  signum      = liftWord1 signum
  fromInteger i = Word (normWordI i)

instance Real Word where
  toRational x = toRational (toInteger x)

instance Enum Word where
  succ x | x == maxBound = error "Enum.succ{Word}: tried to take `succ' of maxBound"
         | otherwise     = x + 1
  pred x | x == minBound = error "Enum.pred{Word}: tried to take `pred' of minBound"
         | otherwise     = x - 1
  toEnum i | toInteger i >= toInteger (minBound :: Word) && toInteger i <= toInteger (maxBound :: Word)
                       = fromIntegral i
           | otherwise = error "Enum.toEnum{Word}: tag is outside of bounds"
  fromEnum x = fromInteger (toInteger x)
  enumFrom x = enumFromTo x maxBound
  enumFromThen x y = enumFromThenTo x y (if y >= x then maxBound else minBound)
  enumFromTo x y = map fromInteger [toInteger x .. toInteger y]
  enumFromThenTo x y z = map fromInteger [toInteger x, toInteger y .. toInteger z]

instance Integral Word where
  quot (Word x) (Word y) = Word (normWord (quot x y))
  rem (Word x) (Word y)  = Word (normWord (rem x y))
  div (Word x) (Word y)  = Word (normWord (div x y))
  mod (Word x) (Word y)  = Word (normWord (mod x y))
  quotRem x y = (quot x y, rem x y)
  divMod x y  = (div x y, mod x y)
  toInteger (Word x) = toInteger x

instance Ix Word where
  range (a, b)     = [a .. b]
  index (a, b) i
    | a <= i && i <= b = fromInteger (toInteger i - toInteger a)
    | otherwise        = error "Ix.index{Word}: index out of range"
  inRange (a, b) i = a <= i && i <= b

instance Bits Word where
  (.&.)        = liftWord2 (.&.)
  (.|.)        = liftWord2 (.|.)
  xor          = liftWord2 xor
  complement   = liftWord1 complement
  shift (Word x) i = Word (normWord (shift x i))
  rotate (Word x) i = let { j = i `mod` 64; u = x }
                     in Word (normWord ((u `shiftL` j) .|. (u `shiftR` (64 - j))))
  testBit (Word x) i = i < 64 && testBit x i
  bitSize _    = 64
  isSigned _   = False
  popCount (Word x) = popCount x
