-- Foreign.C.Error: the Haskell 2010 library module (Report 2010, chapter
-- 27), for Yale Haskell's Haskell 98 dialect.  The values of the E*
-- constants are this system's (src/ffi/errno-<os>.lisp, generated by
-- tools/gen/gen-errno.sh); those it lacks are Errno (-1), which is not a
-- valid errno and equals no Errno, as in GHC.  errno is read through
-- libc, so it is what the last C call (or the Lisp runtime after it) set.
module Foreign.C.Error (
    Errno(Errno), eOK,
    e2BIG, eACCES, eADDRINUSE, eADDRNOTAVAIL, eADV, eAFNOSUPPORT, eAGAIN, eALREADY, eBADF, eBADMSG, eBADRPC, eBUSY, eCHILD, eCOMM, eCONNABORTED, eCONNREFUSED, eCONNRESET, eDEADLK, eDESTADDRREQ, eDIRTY, eDOM, eDQUOT, eEXIST, eFAULT, eFBIG, eFTYPE, eHOSTDOWN, eHOSTUNREACH, eIDRM, eILSEQ, eINPROGRESS, eINTR, eINVAL, eIO, eISCONN, eISDIR, eLOOP, eMFILE, eMLINK, eMSGSIZE, eMULTIHOP, eNAMETOOLONG, eNETDOWN, eNETRESET, eNETUNREACH, eNFILE, eNOBUFS, eNODATA, eNODEV, eNOENT, eNOEXEC, eNOLCK, eNOLINK, eNOMEM, eNOMSG, eNONET, eNOPROTOOPT, eNOSPC, eNOSR, eNOSTR, eNOSYS, eNOTBLK, eNOTCONN, eNOTDIR, eNOTEMPTY, eNOTSOCK, eNOTTY, eNXIO, eOPNOTSUPP, ePERM, ePFNOSUPPORT, ePIPE, ePROCLIM, ePROCUNAVAIL, ePROGMISMATCH, ePROGUNAVAIL, ePROTO, ePROTONOSUPPORT, ePROTOTYPE, eRANGE, eREMCHG, eREMOTE, eROFS, eRPCMISMATCH, eRREMOTE, eSHUTDOWN, eSOCKTNOSUPPORT, eSPIPE, eSRCH, eSRMNT, eSTALE, eTIME, eTIMEDOUT, eTOOMANYREFS, eTXTBSY, eUSERS, eWOULDBLOCK, eXDEV,
    isValidErrno, getErrno, resetErrno, errnoToIOError, throwErrno,
    throwErrnoIf, throwErrnoIf_, throwErrnoIfRetry, throwErrnoIfRetry_,
    throwErrnoIfMinus1, throwErrnoIfMinus1_, throwErrnoIfMinus1Retry,
    throwErrnoIfMinus1Retry_, throwErrnoIfNull, throwErrnoIfNullRetry,
    throwErrnoIfRetryMayBlock, throwErrnoIfRetryMayBlock_,
    throwErrnoIfMinus1RetryMayBlock, throwErrnoIfMinus1RetryMayBlock_,
    throwErrnoIfNullRetryMayBlock,
    throwErrnoPath, throwErrnoPathIf, throwErrnoPathIf_,
    throwErrnoPathIfNull, throwErrnoPathIfMinus1, throwErrnoPathIfMinus1_
  ) where

import ForeignPrims
import IOPrims (primStdin)
import IOBase (Handle(..))
import PreludeIO (IOError(..))
import Foreign.Ptr
import Foreign.C.Types

newtype Errno = Errno CInt

instance Eq Errno where
  e1@(Errno n1) == e2@(Errno n2)
    | isValidErrno e1 && isValidErrno e2 = n1 == n2
    | otherwise                          = False

isValidErrno :: Errno -> Bool
isValidErrno (Errno n) = n /= -1

errno :: String -> Errno
errno name = Errno (fromIntegral (primErrnoValue name))

eOK :: Errno
eOK = Errno 0

e2BIG, eACCES, eADDRINUSE, eADDRNOTAVAIL, eADV, eAFNOSUPPORT, eAGAIN, eALREADY, eBADF, eBADMSG, eBADRPC, eBUSY, eCHILD, eCOMM, eCONNABORTED, eCONNREFUSED, eCONNRESET, eDEADLK, eDESTADDRREQ, eDIRTY, eDOM, eDQUOT, eEXIST, eFAULT, eFBIG, eFTYPE, eHOSTDOWN, eHOSTUNREACH, eIDRM, eILSEQ, eINPROGRESS, eINTR, eINVAL, eIO, eISCONN, eISDIR, eLOOP, eMFILE, eMLINK, eMSGSIZE, eMULTIHOP, eNAMETOOLONG, eNETDOWN, eNETRESET, eNETUNREACH, eNFILE, eNOBUFS, eNODATA, eNODEV, eNOENT, eNOEXEC, eNOLCK, eNOLINK, eNOMEM, eNOMSG, eNONET, eNOPROTOOPT, eNOSPC, eNOSR, eNOSTR, eNOSYS, eNOTBLK, eNOTCONN, eNOTDIR, eNOTEMPTY, eNOTSOCK, eNOTTY, eNXIO, eOPNOTSUPP, ePERM, ePFNOSUPPORT, ePIPE, ePROCLIM, ePROCUNAVAIL, ePROGMISMATCH, ePROGUNAVAIL, ePROTO, ePROTONOSUPPORT, ePROTOTYPE, eRANGE, eREMCHG, eREMOTE, eROFS, eRPCMISMATCH, eRREMOTE, eSHUTDOWN, eSOCKTNOSUPPORT, eSPIPE, eSRCH, eSRMNT, eSTALE, eTIME, eTIMEDOUT, eTOOMANYREFS, eTXTBSY, eUSERS, eWOULDBLOCK, eXDEV :: Errno
e2BIG = errno "E2BIG"
eACCES = errno "EACCES"
eADDRINUSE = errno "EADDRINUSE"
eADDRNOTAVAIL = errno "EADDRNOTAVAIL"
eADV = errno "EADV"
eAFNOSUPPORT = errno "EAFNOSUPPORT"
eAGAIN = errno "EAGAIN"
eALREADY = errno "EALREADY"
eBADF = errno "EBADF"
eBADMSG = errno "EBADMSG"
eBADRPC = errno "EBADRPC"
eBUSY = errno "EBUSY"
eCHILD = errno "ECHILD"
eCOMM = errno "ECOMM"
eCONNABORTED = errno "ECONNABORTED"
eCONNREFUSED = errno "ECONNREFUSED"
eCONNRESET = errno "ECONNRESET"
eDEADLK = errno "EDEADLK"
eDESTADDRREQ = errno "EDESTADDRREQ"
eDIRTY = errno "EDIRTY"
eDOM = errno "EDOM"
eDQUOT = errno "EDQUOT"
eEXIST = errno "EEXIST"
eFAULT = errno "EFAULT"
eFBIG = errno "EFBIG"
eFTYPE = errno "EFTYPE"
eHOSTDOWN = errno "EHOSTDOWN"
eHOSTUNREACH = errno "EHOSTUNREACH"
eIDRM = errno "EIDRM"
eILSEQ = errno "EILSEQ"
eINPROGRESS = errno "EINPROGRESS"
eINTR = errno "EINTR"
eINVAL = errno "EINVAL"
eIO = errno "EIO"
eISCONN = errno "EISCONN"
eISDIR = errno "EISDIR"
eLOOP = errno "ELOOP"
eMFILE = errno "EMFILE"
eMLINK = errno "EMLINK"
eMSGSIZE = errno "EMSGSIZE"
eMULTIHOP = errno "EMULTIHOP"
eNAMETOOLONG = errno "ENAMETOOLONG"
eNETDOWN = errno "ENETDOWN"
eNETRESET = errno "ENETRESET"
eNETUNREACH = errno "ENETUNREACH"
eNFILE = errno "ENFILE"
eNOBUFS = errno "ENOBUFS"
eNODATA = errno "ENODATA"
eNODEV = errno "ENODEV"
eNOENT = errno "ENOENT"
eNOEXEC = errno "ENOEXEC"
eNOLCK = errno "ENOLCK"
eNOLINK = errno "ENOLINK"
eNOMEM = errno "ENOMEM"
eNOMSG = errno "ENOMSG"
eNONET = errno "ENONET"
eNOPROTOOPT = errno "ENOPROTOOPT"
eNOSPC = errno "ENOSPC"
eNOSR = errno "ENOSR"
eNOSTR = errno "ENOSTR"
eNOSYS = errno "ENOSYS"
eNOTBLK = errno "ENOTBLK"
eNOTCONN = errno "ENOTCONN"
eNOTDIR = errno "ENOTDIR"
eNOTEMPTY = errno "ENOTEMPTY"
eNOTSOCK = errno "ENOTSOCK"
eNOTTY = errno "ENOTTY"
eNXIO = errno "ENXIO"
eOPNOTSUPP = errno "EOPNOTSUPP"
ePERM = errno "EPERM"
ePFNOSUPPORT = errno "EPFNOSUPPORT"
ePIPE = errno "EPIPE"
ePROCLIM = errno "EPROCLIM"
ePROCUNAVAIL = errno "EPROCUNAVAIL"
ePROGMISMATCH = errno "EPROGMISMATCH"
ePROGUNAVAIL = errno "EPROGUNAVAIL"
ePROTO = errno "EPROTO"
ePROTONOSUPPORT = errno "EPROTONOSUPPORT"
ePROTOTYPE = errno "EPROTOTYPE"
eRANGE = errno "ERANGE"
eREMCHG = errno "EREMCHG"
eREMOTE = errno "EREMOTE"
eROFS = errno "EROFS"
eRPCMISMATCH = errno "ERPCMISMATCH"
eRREMOTE = errno "ERREMOTE"
eSHUTDOWN = errno "ESHUTDOWN"
eSOCKTNOSUPPORT = errno "ESOCKTNOSUPPORT"
eSPIPE = errno "ESPIPE"
eSRCH = errno "ESRCH"
eSRMNT = errno "ESRMNT"
eSTALE = errno "ESTALE"
eTIME = errno "ETIME"
eTIMEDOUT = errno "ETIMEDOUT"
eTOOMANYREFS = errno "ETOOMANYREFS"
eTXTBSY = errno "ETXTBSY"
eUSERS = errno "EUSERS"
eWOULDBLOCK = errno "EWOULDBLOCK"
eXDEV = errno "EXDEV"

getErrno :: IO Errno
getErrno = do
  n <- primGetErrno
  return (Errno (fromIntegral n))

resetErrno :: IO ()
resetErrno = primSetErrno 0

-- An IOError for the errno, its kind as GHC classifies it and its
-- description strerror's.
errnoToIOError :: String -> Errno -> Maybe Handle -> Maybe String -> IOError
errnoToIOError loc (Errno n) mh mpath =
  IOError (primErrnoIOError loc (fromIntegral n)
                            (isJust' mh) (handleObj mh)
                            (isJust' mpath) (maybe "" id mpath))
  where isJust' (Just _) = True
        isJust' Nothing  = False
        handleObj (Just (Handle h)) = h
        handleObj Nothing           = primStdin   -- unused

throwErrno :: String -> IO a
throwErrno loc = do
  e <- getErrno
  ioError (errnoToIOError loc e Nothing Nothing)

throwErrnoIf :: (a -> Bool) -> String -> IO a -> IO a
throwErrnoIf failed loc act = do
  r <- act
  if failed r then throwErrno loc else return r

throwErrnoIf_ :: (a -> Bool) -> String -> IO a -> IO ()
throwErrnoIf_ failed loc act = throwErrnoIf failed loc act >> return ()

-- The Retry forms repeat the action while it fails with EINTR.
throwErrnoIfRetry :: (a -> Bool) -> String -> IO a -> IO a
throwErrnoIfRetry failed loc act = do
  r <- act
  if failed r
    then do e <- getErrno
            if e == eINTR then throwErrnoIfRetry failed loc act
                          else throwErrno loc
    else return r

throwErrnoIfRetry_ :: (a -> Bool) -> String -> IO a -> IO ()
throwErrnoIfRetry_ failed loc act = throwErrnoIfRetry failed loc act >> return ()

-- The MayBlock forms also run on_block, then retry, when the action
-- fails with EAGAIN or EWOULDBLOCK.
throwErrnoIfRetryMayBlock :: (a -> Bool) -> String -> IO a -> IO b -> IO a
throwErrnoIfRetryMayBlock failed loc act onBlock = do
  r <- act
  if failed r
    then do e <- getErrno
            if e == eINTR
              then throwErrnoIfRetryMayBlock failed loc act onBlock
              else if e == eWOULDBLOCK || e == eAGAIN
                then onBlock >> throwErrnoIfRetryMayBlock failed loc act onBlock
                else throwErrno loc
    else return r

throwErrnoIfRetryMayBlock_ :: (a -> Bool) -> String -> IO a -> IO b -> IO ()
throwErrnoIfRetryMayBlock_ failed loc act onBlock =
  throwErrnoIfRetryMayBlock failed loc act onBlock >> return ()

throwErrnoIfMinus1 :: (Eq a, Num a) => String -> IO a -> IO a
throwErrnoIfMinus1 = throwErrnoIf (== -1)

throwErrnoIfMinus1_ :: (Eq a, Num a) => String -> IO a -> IO ()
throwErrnoIfMinus1_ = throwErrnoIf_ (== -1)

throwErrnoIfMinus1Retry :: (Eq a, Num a) => String -> IO a -> IO a
throwErrnoIfMinus1Retry = throwErrnoIfRetry (== -1)

throwErrnoIfMinus1Retry_ :: (Eq a, Num a) => String -> IO a -> IO ()
throwErrnoIfMinus1Retry_ = throwErrnoIfRetry_ (== -1)

throwErrnoIfMinus1RetryMayBlock :: (Eq a, Num a) => String -> IO a -> IO b -> IO a
throwErrnoIfMinus1RetryMayBlock = throwErrnoIfRetryMayBlock (== -1)

throwErrnoIfMinus1RetryMayBlock_ :: (Eq a, Num a) => String -> IO a -> IO b -> IO ()
throwErrnoIfMinus1RetryMayBlock_ = throwErrnoIfRetryMayBlock_ (== -1)

throwErrnoIfNull :: String -> IO (Ptr a) -> IO (Ptr a)
throwErrnoIfNull = throwErrnoIf (== nullPtr)

throwErrnoIfNullRetry :: String -> IO (Ptr a) -> IO (Ptr a)
throwErrnoIfNullRetry = throwErrnoIfRetry (== nullPtr)

throwErrnoIfNullRetryMayBlock :: String -> IO (Ptr a) -> IO b -> IO (Ptr a)
throwErrnoIfNullRetryMayBlock = throwErrnoIfRetryMayBlock (== nullPtr)

-- The Path forms name the file in the IOError.
throwErrnoPath :: String -> FilePath -> IO a
throwErrnoPath loc path = do
  e <- getErrno
  ioError (errnoToIOError loc e Nothing (Just path))

throwErrnoPathIf :: (a -> Bool) -> String -> FilePath -> IO a -> IO a
throwErrnoPathIf failed loc path act = do
  r <- act
  if failed r then throwErrnoPath loc path else return r

throwErrnoPathIf_ :: (a -> Bool) -> String -> FilePath -> IO a -> IO ()
throwErrnoPathIf_ failed loc path act = throwErrnoPathIf failed loc path act >> return ()

throwErrnoPathIfNull :: String -> FilePath -> IO (Ptr a) -> IO (Ptr a)
throwErrnoPathIfNull = throwErrnoPathIf (== nullPtr)

throwErrnoPathIfMinus1 :: (Eq a, Num a) => String -> FilePath -> IO a -> IO a
throwErrnoPathIfMinus1 = throwErrnoPathIf (== -1)

throwErrnoPathIfMinus1_ :: (Eq a, Num a) => String -> FilePath -> IO a -> IO ()
throwErrnoPathIfMinus1_ = throwErrnoPathIf_ (== -1)
